#!/bin/sh
#
# $FML: post_configure,v 1.2 2003/01/17 09:22:02 fukachan Exp $
#

set -x

tmp=$PWD/tmp.zebra.$$

trap "rm -f $tmp" 0 1 3 15

XPWD=`pwd`

rm -f $tmp;
   
(
   cd pkg/zebra;
   
   for dir in zebra bgpd ripng
   do
      (
   	cd $dir || exit 1
   
   	echo "# $dir";
   	echo progs   $dir
   	echo special $dir srcdir ../pkg/zebra/$dir
   	echo special $dir objdir pkg/zebra/$dir
   	echo special $dir objs *.o
   
   	cd ..
   	echo special $dir objpaths $PWD/$dir/*.o $PWD/lib/*.o |\
   	sed "s@${XPWD}@\$\{CURDIR\}@g"
   
   	echo ""; echo "";
       ) >> $tmp
   done

)

mv $tmp zebra.rules

sed -e '/__ZEBRA__/r zebra.rules' -e '/__ZEBRA__/d' ramdiskbin.conf > ramdiskbin.conf.new.$$
mv ramdiskbin.conf.new.$$ ramdiskbin.conf

exit 0
