#undef PACKAGE
#undef JFTPGW_VERSION
#undef HAVE_SOCKLEN_T
#undef CONFPATH
#undef PID_T_SIGNED
#undef HAVE_CRYPT
#undef HAVE_LIBWRAP
#undef SFTP_SUPPORT
#undef SFTPSERV_PATH
#undef LINK_AS_LIBRARY
#undef WINDOWS

#undef HAVE_SNPRINTF
#undef HAVE_VSNPRINTF

#undef HAVE_LOG_FACILITY_LOG_AUTH
#undef HAVE_LOG_FACILITY_LOG_AUTHPRIV
#undef HAVE_LOG_FACILITY_LOG_CRON
#undef HAVE_LOG_FACILITY_LOG_DAEMON
#undef HAVE_LOG_FACILITY_LOG_FTP
#undef HAVE_LOG_FACILITY_LOG_KERN
#undef HAVE_LOG_FACILITY_LOG_LOCAL0
#undef HAVE_LOG_FACILITY_LOG_LOCAL1
#undef HAVE_LOG_FACILITY_LOG_LOCAL2
#undef HAVE_LOG_FACILITY_LOG_LOCAL3
#undef HAVE_LOG_FACILITY_LOG_LOCAL4
#undef HAVE_LOG_FACILITY_LOG_LOCAL5
#undef HAVE_LOG_FACILITY_LOG_LOCAL6
#undef HAVE_LOG_FACILITY_LOG_LOCAL7
#undef HAVE_LOG_FACILITY_LOG_LPR
#undef HAVE_LOG_FACILITY_LOG_MAIL
#undef HAVE_LOG_FACILITY_LOG_NEWS
#undef HAVE_LOG_FACILITY_LOG_SYSLOG
#undef HAVE_LOG_FACILITY_LOG_USER
#undef HAVE_LOG_FACILITY_LOG_UUCP
#undef HAVE_LOG_FACILITY_LOG_CONSOLE
#undef HAVE_LOG_FACILITY_LOG_SECURITY

#undef HAVE_SIOCGIFADDR
#undef HAVE_SIOCGIFCONF

#undef HAVE_ICMP_SUPPORT

