#
# Copyright (C) 2001 Ken'ichi Fukamachi <fukachan@fml.org>
#
# All rights reserved. This program is free software; you can
# redistribute it and/or modify it under the same terms as NetBSD itself.
#
# $FML: Makefile,v 1.3 2001/09/29 08:15:42 fukachan Exp $
#

CFLAGS = -I ${BSDSRCDIR}/usr.sbin/dhcp/includes

__h_errno_set.o: __h_errno_set.c
	${CC} ${CFLAGS} -c __h_errno_set.c
